[package]
name = "catalog"
version = "0.1.0"
authors = ["Casper Rogild Storm"]
edition = "2018"

[workspace]
members = [
    ".",
    "crates/backend"
]

[dependencies]
backend = { path = "crates/backend" }
structopt = "0.3.21"
futures = "0.3.15"
serde_json = "1.0.64"
