[package]
name = "source"
version = "0.1.0"
authors = ["Casper Rogild Storm"]
edition = "2018"

[dependencies]
thiserror = "1.0"
async-trait = "0.1.50"
async-std = "1.9.0"
isahc = { version = "1.4.0", features=[ 'json' ] }
serde = "1.0.126"
serde_json = "1.0.64"