on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch addon data
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p cli --release
      - name: Generate Catalog
        run: |
          ./target/release/cli catalog
      # - name: Commit
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add catalog-0.1.0.json
      #     git commit -m "chore: updated catalog"
      #     git push
      - name: Test
        run: |
          jq '. | length' ./catalog-0.1.0.json